### ISSUE TITLE
Crashed - when load more API was calling at the same time click on ExpandableLayout

### ISSUE THREAD

**Issue by vandanabpatel** [hendraanggrian/ExpandableLayoutRecyclerView#3]
java.lang.NullPointerException: Attempt to invoke virtual method 'void com.unoapp.dirtybird.ui.custom.expandable_recyclerview.ExpandableLayout.hide()' on a null object reference
                      at com.unoapp.dirtybird.ui.custom.expandable_recyclerview.ExpandableRecyclerView$Adapter$1.onClick(ExpandableRecyclerView.java:65)
                      at android.view.View.performClick(View.java:5733)
                      at android.view.View$PerformClick.run(View.java:22880)
                      at android.os.Handler.handleCallback(Handler.java:836)
                      at android.os.Handler.dispatchMessage(Handler.java:103)
                      at android.os.Looper.loop(Looper.java:203)
                      at android.app.ActivityThread.main(ActivityThread.java:6251)
                      at java.lang.reflect.Method.invoke(Native Method)
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1088)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:949)

**Comment by hanggrian** [comment]
This library might not be suitable for newer Android releases. Please refer to other available solutions while I patch this library (might take some time though).

I'll reply when I have any update.

**Comment by titiarimba** [comment]
Hi @hendraanggrian thanks for this awesome library. good job! i hope you can always maintenance and keep it up to date 👍

**Comment by amrafridi29** [comment]
how to change the backhground color of clicked row item ?
